### ISSUE TITLE
Install VTE

### ISSUE THREAD

**Issue by mirestrepo** [brown-ccv/docker-stacks#2]
When launching the Julia containers on FastX we get `bash: _vte_prompt_command: not found`

We need to install vte3 and vte-profile

Related google searches:
https://groups.google.com/a/lbl.gov/forum/#!msg/singularity/KczsNTef87s/BSTSCiiBBAAJ
https://stackoverflow.com/questions/22281875/bash-vte-prompt-command-command-not-found

**Comment by mcmcgrath13** [comment]
On it

**Comment by mcmcgrath13** [comment]
Resolved-ish.  Instead of installing VTE, I overwrote the ENV variable looking for VTE.
